snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/24/32.yaml

packages:
- pithia-client
- pithia-core
- pithia-effectful

# extra-deps: []

system-ghc: true
